services:
  node-app:
    build:
      context: .
      target: development
    environment:
        - NODE_ENV=development
    volumes:
      - ./src:/app/src
#    command:
#      - npm run start-dev